# Generated by Django 4.2.4 on 2023-09-13 21:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sysnam', models.CharField(max_length=300)),
                ('org_name', models.CharField(max_length=300)),
                ('person_kind', models.CharField(max_length=100)),
                ('rank_from', models.PositiveIntegerField()),
                ('rank_to', models.PositiveIntegerField()),
                ('work_quality', models.CharField(max_length=4000)),
                ('work_item', models.CharField(max_length=2000, null=True)),
                ('work_addr', models.CharField(max_length=2000, null=True)),
                ('is_resume_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysnam', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('num', models.PositiveSmallIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '簡任'), (2, '薦任'), (3, '委任')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place_id', models.PositiveSmallIntegerField()),
                ('work_place_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sysnam', models.CharField(max_length=300)),
                ('org_name', models.CharField(max_length=300)),
                ('person_kind', models.CharField(max_length=100)),
                ('rank_from', models.PositiveIntegerField()),
                ('rank_to', models.PositiveIntegerField()),
                ('num', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('work_places_id', models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('is_handicap', models.BooleanField()),
                ('is_orig', models.BooleanField()),
                ('is_local_orig', models.BooleanField()),
                ('is_training', models.BooleanField()),
                ('job_type', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=2000, null=True)),
                ('work_quality', models.CharField(max_length=4000)),
                ('work_item', models.CharField(max_length=2000, null=True)),
                ('work_addr', models.CharField(max_length=2000, null=True)),
                ('contact', models.CharField(max_length=4000, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('view_url', models.CharField(max_length=400)),
                ('isExpiring', models.BooleanField()),
                ('history_count', models.PositiveSmallIntegerField()),
                ('is_resume_required', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
